InternLM/InternLM

doc/en/train_performance.md, doc/train_performance.md, internlm/core/no_pipeline_scheduler.py
- There is no need to keep out data and label data in no_pp_scheduler. This would dramatically increase cuda memory usage. If micro_num is large, the training process would crash due to OOM err.
- We also update the training performance with limited global batch size
=> fix(no_pp_scheduler): drop model out data and label if not used

web_demo.py
* Add the repetition_penalty parameter in the GenerationConfig of web_demo.py, which is used to avoid overly repetitive model generation.
=> feat(web_demo): add repetition_penalty in GenerationConfig in web_demo.py

internlm/initialize/launch.py, internlm/utils/writer.py, train.py
Support TensorBoard writer for recording and visualizing training config infos and some performance metrics.
Add `Writer` Class in `internlm/utils/writer.py` file, and support two public functions `add_scalar()` and `add_text()` for writting scalar value and text string.
User can start writer and set tensorboard folder in `configs/7B_sft.py` file:
```python
enable_tb = True  # Whether to enable writing to TensorBoard, defaults to True
tensorboard_folder = None  # The new log folder for TensorBoard, defaults to None
resume_tb_folder = None  # The old log folder for resuming checkpoint, defaults to None
```
If `tensorboard_folder` is set `None` by user, `tensorboard_folder` will be initialized as `JOB_NAME/launch_time`.
**Before PR**:
=> feat(utils/writer.py): support tensorboard writer

doc/en/install.md, doc/install.md, internlm/solver/lr_scheduler.py, internlm/solver/optimizer/hybrid_zero_optim.py
1. Update code to adapt to torch2.0.
2. Publish [public internlm environment image](https://hub.docker.com/r/sunpengsdu/internlm).
Since torch2.0 has no inf，we use inf in math package:
```python
import math
inf = math.inf
```
In torch2.0, class `CosineAnnealingLR` is inherited from class `LRScheduler`, not `_LRScheduler`:
so the `lr_scheduler` instance should be `_LRScheduler(LRScheduler)` or `CosineAnnealingLR(LRScheduler)`
**Before PR**:
=> feat(solver): fix code to adapt to torch2.0 and provide docker images

internlm/initialize/launch.py, internlm/model/embedding.py, internlm/model/linear.py, internlm/model/modeling_internlm.py, internlm/model/utils.py, internlm/monitor/__init__.py, internlm/monitor/alert.py, internlm/monitor/monitor.py, internlm/monitor/utils.py, internlm/solver/optimizer/hybrid_zero_optim.py, internlm/utils/common.py, internlm/utils/evaluation.py, train.py
Monitor training status, loss value, exception status and so on, send alert info to feishu.
- `monitor/alert.py`: add func `send_feishu_msg_with_webhook` for sending alert info to feishu.
- `monitor/monitor.py`: add func `initialize_monitor` for initializing monitor thread.
User can set feishu webhook alert address in `configs/7B_sft.py`:
```python
alert_address = "xxx"
```
Alert info example is shown as follows:
**Before PR**:
=> feat(monitor): support monitor and alert

.gitignore, internlm/initialize/launch.py, internlm/utils/simple_memory_profiler.py, requirements/runtime.txt, train.py
Monitoring the allocation of GPU memory during the training process is crucial for optimizing the training of LLM. This PR provides a concise and practical solution for GPU memory monitoring that **almost** accurately reflects the actual memory usage.
We implement `SimpleMemoryProfiler` in `internlm/utils/simple_memory_profiler.py` and use it in `train.py`.
The key idea is as follows:
In the field of LLM, GPU memory usage mainly consists of two parts: model data and non-model data. Model data includes model parameters, model gradients, and optimizer states, while non-model data includes activations, communication buffers, and memory blocks that cannot be used due to memory fragmentation. Here, we primarily focus on estimating the GPU memory usage of the four components: model parameters, …
=> feat(profiling): add a simple memory profiler

internlm/initialize/launch.py, internlm/utils/model_checkpoint.py, internlm/utils/storage_manager.py, train.py
For  automatic restart, we need to support automatic loading of the latest ckpt, including NFS or Ceph.
In some cases, we want the training task to quit and save one ckpt in the same time.
```
M       internlm/initialize/launch.py
M       internlm/utils/model_checkpoint.py
M       internlm/utils/storage_manager.py
M       train.py
````
TODO
TODO
**Before PR**:
**After PR**:
=> feat(ckpt): add auto checkpoint load and singal quit

internlm/core/scheduler/base_scheduler.py, train.py
Fix scheduler metric hook skip error.
**Before PR**:
=> fix(train.py): fix scheduler metric hook skip error

internlm/core/trainer.py
Fix loading model checkpointing error.
`core/trainer.py`: skip streaming train state resume batch sampler in class `TrainState::load_state_dict`.
**Before PR**:
=> fix(core/trainer.py): fix streaming train state load error

internlm/model/metrics.py
In the call to AccPerplex, if `reset=False`, the loss metrics will still be reset. To address this, the `reset` argument needs to be passed to `LossWithTypeId::get_metric`.
/internlm/model/metrics.py: add `reset` argument when calling the `LossWithTypeId::get_metric` in line 179.
**Before PR**:
=> fix(metric): reset argument missing in getting loss metrics.

doc/code-docs/requirements.txt, doc/code-docs/source/conf.py
Fix autodoc works locally, but does not on the ReadTheDocs.
**Before PR**:
=> fix(doc/code-docs): autodoc shown error

internlm/core/context/parallel_context.py, internlm/core/context/process_group_initializer.py, internlm/train/training_internlm.py, train.py
Since the random state will be different in different tensor parallel device of the same data parallel group, here we do not set the random state mode to ParallelMode.Data until model is built(instead, we use a dummy mode during model construction and switch the random state to ParallelMode.Data when model is built). The underlying reason is that the device of tp_rank = 0 will perform additional random operations during the RowParallelLinear module building process.
internlm/core/context/process_group_initializer.py: add dummy mode in line 39.
internlm/core/context/parallel_context.py: set seed for dummy mode in line 529 and set to dummy mode in line 541
internlm/train/training_internlm.py:  set random state to data mode when model is built in line 86
Does the modification introduce …
=> fix(core/context): use dummy mode to generate random numbers in model construction

internlm/core/context/parallel_context.py, internlm/core/context/process_group_initializer.py, internlm/core/scheduler/no_pipeline_scheduler.py, internlm/core/scheduler/pipeline_scheduler.py, internlm/initialize/launch.py, internlm/solver/optimizer/hybrid_zero_optim.py, internlm/train/training_internlm.py, internlm/utils/logger.py, internlm/utils/model_checkpoint.py, internlm/utils/timeout.py, tests/test_utils/common_fixture.py, tests/test_utils/test_timeout.py
In order to better locate where the user code hangs, we added a timeout decorator to the key training functions. And the timeout parameter is set at nccl init_process_group. If you want to enable nccl timeout and siganl timeout, please set environment variables `INTERNLM_ENABLE_TIMEOUT=1` and `NCCL_ASYNC_ERROR_HANDLING=1` before training.
**Before PR**:
**After PR**:
=> Feat(utils): add timeout warpper

tools/transformers/modeling_internlm.py
The "stream_chat" just return an tuple like (response, history), but stream_chat was supposed to return generator. 
You can refer to function ”def stream_chat“ in https://huggingface.co/THUDM/chatglm-6b/blob/main/modeling_chatglm.py#L1316  return "yield response, new_history"
And project https://github.com/imClumsyPanda/langchain-ChatGLM expect function ”def stream_chat“ to return a generator.
But the implementation in chatglm-6b reuse many logic in huggingface transformers function "def generate" in …
=> fix(chat): fix stream_chat to return generator

tools/transformers/convert2hf.py
Fix KeyError that occurred in [convert2hf.py](https://github.com/InternLM/InternLM/blob/main/tools/transformers/convert2hf.py#L41).
I also meet the problem that [issue](https://github.com/InternLM/InternLM/issues/296) reports.
Add a default value `None` to the `states.pop` function. 
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with …
=> fix(convert2hf.py): fix the `rotary_emb.inv_freq` KeyError

internlm/train/training_internlm.py
There is a bug for dense training in `internlm/train/training_internlm.py`.
Fix the moe_loss as none for recording into panel_metrics in `internlm/train/training_internlm.py`.
No.
No.
**Before PR**:
**After PR**:
=> fix(record): fix moe_loss as none for panel_metrics

internlm/core/context/parallel_context.py, internlm/initialize/launch.py, internlm/solver/optimizer/hybrid_zero_optim.py, internlm/solver/optimizer/store.py, internlm/train/training_internlm.py, internlm/utils/model_checkpoint.py, internlm/utils/parallel.py
Make MoE available  when number of experts is smaller than dp size. In this case, each expert is shared between its local dp group, e.g. when global dp size is 4 (the devices are labeled as 0,1,2,3) and number of experts is 2, then devices 0 and 2 will have shared  expert A, devices 1 and 3 will have shared  expert B. 
1. parallel_context.py: set expert communication group and expert_data communication group. The expert group will perform all-to-all communication …
=> feat(moe): add  local data parallel support for experts

internlm/initialize/launch.py, internlm/solver/optimizer/hybrid_zero_optim.py, internlm/solver/optimizer/store.py, internlm/solver/optimizer/utils.py, internlm/train/utils.py, internlm/utils/model_checkpoint.py, internlm/utils/parallel.py, tests/test_utils/test_model_checkpoint.py
* add zero1 feature for expert local dp. 
* now each parameter group has its own dp_mode. For  moe experts, its dp_mode is EXPERT_DATA, while for other groups, its dp_mode is DATA. The optimizer will perform different behaviors according to dp_mode.
* do not support expert zero1 and overlap both at the same time for now 
1. train.utils.py: add dp_mode attributes for different parameter group
2. hybrid_zero_optim.py (partition param):  
* each parameter groups has its own _zero_local_rank, _zero_world_size, …
=> feat(moe):support zero for expert local dp

internlm/utils/writer.py
allow `resume_tb_folder` to be an empty string, related to https://github.com/pjlab-sys4nlp/train_internlm/issues/231
**Before PR**:
**After PR**:
=> fix(init): allow resume_tb_folder to be an empty string

internlm/utils/gputest.py
Runtime benchmark diagnosis can easily cause the training process to exit due to NCCL errors. We will temporarily disable nccl diagnosis to avoid affecting user tasks. Need to fundamentally solve this problem in the future.
**Before PR**:
**After PR**:
=> fix(utils): disable runtime nccl diagnosis

internlm/core/trainer.py
When the volcano cloud model loads ckpt for continued training, there will be a tensorboard segmentation problem. The reason is that the tb path of the volcano itself is special.
Sdd tensorboard path on petrelfs for volc.
**Before PR**:
**After PR**:
=> Fix(trainer):  Save tensorboard path on petrelfs for volc

internlm/initialize/launch.py, internlm/model/modeling_moe.py, internlm/model/utils.py, internlm/moe/sharded_moe.py, internlm/solver/optimizer/hybrid_zero_optim.py, internlm/solver/optimizer/utils.py, internlm/train/utils.py
since calling wait() does not guarantee completing the entire broadcast process, it may cause some problems. Also see:
[1] [synchronous-and-asynchronous-collective-operations in pytorch](https://pytorch.org/docs/stable/distributed.html#synchronous-and-asynchronous-collective-operations)
[2] [Question about wait() for asynchronous collective operations with NCCL](https://github.com/pytorch/pytorch/issues/68112)
[3] [Does the NCCL operation use the default stream as other …
=>  fix(moe): remove norm&gate force sync

internlm/monitor/monitor.py
修复在未启用轻量监控时，发送execption的问题。
`internlm/monitor/monitor.py`
=> fix(alert): send exception to light monitor only if the server is available

tools/transformers/internlm_model/configuration_internlm.py, tools/transformers/internlm_model/modeling_internlm.py
Support using dynamic ntk rope in transformers.
Mainly modified `InternLM/tools/transformers/internlm_model/modeling_internlm.py`.
Add a new rope class named `InternLMDynamicNTKScalingRotaryEmbedding`.
This feature is enabled by default because the default behavior is the same as the original rope behavior, but when the input or generation length exceeds max_position_embeddings, dynamic ntk's generation results will be better.
User can change the value in the `config.json` to change this behaviour.
For example, change config['rotary']['type'] to `origin`.
=> feat(tools): support dynamic ntk rope in transformers

README-ja-JP.md, README-zh-Hans.md, README.md, internlm/apis/inference.py, tools/load_internlm_model.py, tools/transformers/interface.py, web_demo.py, web_demo_internlm.py
This pr mainly provides function code for loading models in internlm format, as well as corresponding generation scripts and a wen_demo that can be used to directly load internlm models.
Support playing web_demo using internlm architecture instead of loading model checkpoints from huggingface.
1. Add code that can be used for streaming generation;
2. Add support for using multiple eos_token_id as end identifiers;
3. Remove some irrelevant code and comments.
1. Add functions that can be used to load the internlm format model;
2. Add sample code for model generation using internlm format;
Use models in internlm format to play web demos.
Use the following command to run:
```python
torchrun --master_port 12331 --nnodes=1 --node_rank=0 --nproc_per_node=1 -m streamlit run web_demo_internlm.py …
```
=> feat(tools): support origin internlm architecture in web_demo

internlm/train/training_internlm.py, internlm/utils/parallel.py
Add IS_SEQUENCE_PARALLEL check for norm module to adapt with different model so that the norm module could conduct grad all_reduce when sequence_parallel is True.
internlm/train/training_internlm.py
internlm/utils/parallel.py
**Before PR**:
=> fix(model): add IS_SEQUENCE_PARALLEL check for norm module

internlm/data/utils.py, internlm/train/training_internlm.py
when the micro_num=1 and use_flash_attn=False, there is a bug in computing metrics.
The reason is the following: (use_flash_attn=False)
the shape of type_ids should be (micro_num, micro_bsz, max_length). In the unpack function, we can squeeze the first dimension if the first dimension is one. That is, the shape of type_ids could be (micro_bsz, max_length) when micro_num=1, which is incorrect resulting in a bug. The mico_num in the shape of type_ids should be kept though the micro_num is one.
1. internlm/data/utils.py
2. internlm/train/training_internlm.py
**Before PR**:
=> fix(data): fix the unpack for type_ids when use_flash_attn=False

configs/7B_MoE4_sft.py, configs/7B_sft.py, internlm/model/metrics.py
avoid oom in metric calculation using fp32.
add a gpc config option to change dtype for metric calculation.
now default using model type as dtype for metric cacluation
=> fix(metric): add metric dtype control

tools/transformers/modeling_internlm.py
=> fix(chat): fix stream_chat in modeling_internlm(hf) to avoid decode error

configs/7B_sft.py, internlm/initialize/launch.py, internlm/utils/writer.py, train.py
In delay-sensitive training, the writing time overhead of tensorboard is not negligible. We add a new config parameter `queue_max_length` to support batch writing of tensorboard.
```python
monitor = dict(
tensorboard=dict(
queue_max_length=10,
),
)
```
**Before PR**:
**After PR**:
=> feat(logger): add tensorboard key value buffer

.github/workflows/daily_tests.yaml, README.md, README_zh-CN.md, chat/README.md, chat/README_zh-CN.md, requirements.txt
1. the newest internlm2's hf model needs flash_attn, add flash_attn installation in test case workflow
2. the newest internlm2's hf model use transformers's static cache which is supported in version 4.38. Update releated docs. 
test workflow is https://github.com/InternLM/InternLM/actions/runs/9560759361
=> [CI]: Add flash_attn installation in testcase and update transformers requirement
