InternLM/InternLM

- README.md
> doc(README.md): update AutoModelForCausalLM

- README-zh-Hans.md
> Doc(README-zh-Hans.md): update AutoModelForCausalLM 

- README.md
> Doc(README.md): Fix typos

- README-zh-Hans.md
- README.md
As described in the title. This PR  fixes the citation blocks in README.md. The markdown files are also automatically re-formated by the markdownlint.
> [Doc]: fix citation blocks

- .github/ISSUE_TEMPLATE/1_bug-report.yml
- .github/ISSUE_TEMPLATE/2_feature-request.yml
- .github/ISSUE_TEMPLATE/3_bug-report_zh.yml
- .github/ISSUE_TEMPLATE/4_feature-request_zh.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
This PR adds issue template and PR template so that developers could have easier communication with users in issue and PR.
> [Doc]: Add issue template

- .github/ISSUE_TEMPLATE/config.yml
> Fix issue templates

- README-zh-Hans.md
- README.md
> [Doc] Add wechat and discord link in readme

- README-zh-Hans.md
- README.md
Current instruction in README will use FP32 for inference and consume around 30GB GPU memory. Using FP16 half this value. 
If this PR introduces a new feature, it is better to list some use cases here and update …
> Use FP16 for inference

- .github/ISSUE_TEMPLATE/1_bug-report.yml
- .github/ISSUE_TEMPLATE/2_question.yml
- .github/ISSUE_TEMPLATE/3_feature-request.yml
- .github/ISSUE_TEMPLATE/4_document.yml
- .github/ISSUE_TEMPLATE/5_bug-report_zh.yml
- .github/ISSUE_TEMPLATE/6_question_zh.yml
- .github/ISSUE_TEMPLATE/7_feature-request_zh.yml
- .github/ISSUE_TEMPLATE/8_document_zh.yml
Avoid all issues being categorized as 'Bug'
Add more issue template
> [Enchancement] add more options for issue template

- README-zh-Hans.md
- README.md
fix #83 
Delete paramter `torch_dtype`
**Before PR**:
**After PR**:
> docs(README): delete parameter `torch_dtype` in README's example code

- web_demo.py
Remove meaningless log.
Fix issue #88 .
Remove the extra print code.
> fix: remove meaningless log in web_demo.py

- tools/alpaca_tokenizer.py
fix #101 
- tools/alpaca_tokenizer.py
No
**Before PR**:
**After PR**:
> [Fix]Fix wrong string cutoff in the script for sft text tokenizing

- tools/transformers/convert2hf.py
`AutoModel` in `auto_map` should be mapped to `InternLMForCausalLM`. #107 
Make `AutoModel` map to `InternLMForCausalLM`
**Before PR**:
**After PR**:
> fix(tools/transformers/convert2hf.py): fix AutoModel's map to InternLMForCausalLM

- tools/alpaca_tokenizer.py
> [Fix] variables are not printed as expected

- .github/workflows/demo_in_readme.yaml
- ci_scripts/common/basic_func.sh
- ci_scripts/data/tokenizer_alpaca.sh
- ci_scripts/data/tokenizer_chinese.sh
- ci_scripts/model/convert_to_hf.sh
- ci_scripts/model/demo_load_7B_chat_model.py
- ci_scripts/model/loaded_as_transformer.py
- ci_scripts/train/ci_7B_sft.py
- ci_scripts/train/slurm_train.sh
- ci_scripts/train/torchrun.sh
1. Dir ci_scripts: add demo test based on readme include dataset preparation, train, convert to hf model and load the InternLM 7B chat model using transformers
2. demo-in-reame.yaml: add trigger event and job
> test(ci_scripts): add demo test based on readme

- web_demo.py
Solve the reason why the GPU memory keeps rising during the dialogue in web_demo.py
Change position of "torch.cuda.empty_cache()" in function "Main"
Change position of "torch.cuda.empty_cache()" in function "Main"
**Before PR**:
**After PR**:
> fix web_demo cache accelerate

- internlm/solver/optimizer/utils.py
Fix code lint error.
**Before PR**:
> style(solver/optimizer/utils.py): fix lint error

- configs/7B_sft.py
- internlm/core/scheduler/no_pipeline_scheduler.py
- internlm/core/scheduler/pipeline_scheduler.py
- internlm/data/packed_dataset.py
- internlm/data/utils.py
- internlm/initialize/initialize_trainer.py
- internlm/model/metrics.py
- internlm/model/modeling_internlm.py
- internlm/model/multi_head_attention.py
- train.py
Support not-flash-attn for pp and no-pp
**Before PR**:
> feat(*): support not-flash-attn for pp and no-pp

- README-zh-Hans.md
- README.md
To resolve #134 
**Before PR**:
**After PR**:
> [Doc] update deployment guide to keep consistency with lmdeploy

- internlm/initialize/launch.py
Set default value for use_flash_attn
**Before PR**:
> fix(initialize/launch.py): set default value for use_flash_attn

- .github/workflows/demo_in_readme.yaml
- ci_scripts/data/tokenizer_chinese.sh
- ci_scripts/train/slurm_train.sh
- ci_scripts/train/torchrun.sh
> test(ci_scripts): use llm partition

- .github/workflows/demo_in_readme.yaml
- ci_scripts/common/basic_func.sh
- ci_scripts/common/variables.sh
- ci_scripts/data/tokenizer_alpaca.sh
- ci_scripts/data/tokenizer_chinese.sh
- ci_scripts/model/convert_to_hf.sh
- ci_scripts/model/demo_load_7B_chat_model.py
- ci_scripts/model/loaded_as_transformer.py
- ci_scripts/train/slurm_train.sh
- ci_scripts/train/torchrun.sh
Optimize the ci scripts.
- remove the function of file existence check.
- update the function of file number check.
- clean test data after test.
- optimize variable and function definition.
If this PR introduces a new feature, it is better to list some use cases here and …
> test(ci_scripts): clean test data after test, remove unnecessary global variables, and other optimizations

- configs/7B_sft.py
- internlm/core/communication/__init__.py
- internlm/core/communication/p2p.py
- internlm/core/communication/utils.py
- internlm/core/naive_amp.py
- internlm/core/scheduler/__init__.py
- internlm/core/scheduler/base_scheduler.py
- internlm/core/scheduler/no_pipeline_scheduler.py
- internlm/core/scheduler/pipeline_scheduler.py
- internlm/initialize/initialize_trainer.py
- internlm/utils/evaluation.py
- internlm/utils/megatron_timers.py
- train.py
Rewrite pipeline scheduler codes to make it more readable，meanwhile we add a new feature for interleaved pipeline scheduler: communication overlap.
* rewrite PipelineScheduler and InterleavedPipelineScheduler
* add communication overlap for InterleavedPipelineScheduler
In config:
* `parallel["pipeline"]["size"]` == `1`: Non-PipelineScheduler is used.
* `parallel["pipeline"]["size"]` > `1` and `model["num_chunks"]` == `1`: PipelineScheduler is used.
* `parallel["pipeline"]["size"]` > `1` and `model["num_chunks"]` > `1` and `parallel["pipeline"]["interleaved_overlap"]` == `True`: InterleavedPipelineScheduler with communication overlap is used.
* `parallel["pipeline"]["size"]` > `1` and `model["num_chunks"]` >= `1` and `parallel["pipeline"]["interleaved_overlap"]` == `False`: …
> refactor(scheduler): rewrite pipeline scheduler

- .github/workflows/demo_in_readme.yaml
- .github/workflows/lint_check.yaml
- ci_scripts/common/variables.sh
1. add install requirements automaticlly for reducing maintenance work
2. add lint check when there is a new PR
3. use default variables in ci_scripts for simplifying the shell scripts 
If this PR introduces a new …
> test(ci_scripts): add install requirements automaticlly,trigger event about lint check and other optimizations

- .github/workflows/stale.yml
Add a workflow for stale PR & Issue  auto remove
- pr & issue well be labeled as stale for inactive in 7 days
- staled PR & Issue  well be remove in 7 days
- run this workflow every day on 1:30 a.m.
> feat(CI_workflow): Add PR & Issue auto remove workflow

- .owners.yml
> feat(bot): Create .owners.yml for Auto Assign

- .github/workflows/demo_in_readme.yaml
- .github/workflows/lint_check.yaml
- ci_scripts/common/post_action.sh
- ci_scripts/data/tokenizer_chinese.sh
- ci_scripts/train/slurm_train.sh
- ci_scripts/train/torchrun.sh
1. add timeout for train job avoiding using the runner resource with long time.
2. add clean work after the slurm job in case the remaining job.
3. mask a part of information about workspace
4. use github-hosted runner on lint check
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep …
> test(ci_scripts): add timeout settings and clean work after the slurm job

- internlm/data/utils.py
- internlm/initialize/launch.py
- internlm/solver/optimizer/hybrid_zero_optim.py
> refactor(solver/optimizer): improve optimizer memory

- tools/pal_inference.py
- tools/transformers/interface.py
- web_demo.py
`generate_interator` in `internlm/utils/interface.py` and `generate_interactive` in `web_demo.py` are almost the same. This PR moves the function to `tools/transformers/interface.py`
If this PR introduces a new …
> refactor(tools): move interface.py and import it to web_demo

- internlm/solver/optimizer/hybrid_zero_optim.py
- internlm/solver/optimizer/utils.py
> update function compute norm

- .gitignore
- internlm/model/norm.py
- internlm/model/utils.py
- internlm/solver/optimizer/hybrid_zero_optim.py
- internlm/solver/optimizer/store.py
- internlm/solver/optimizer/utils.py
- train.py
Overlap gradients last bucket allreduce communication and compute norm.
**Before PR**:
> feat(optimizer/hybrid_zero_optim.py): overlap gradients last bucket allreduce and compute norm

- internlm/core/communication/p2p.py
- internlm/core/communication/utils.py
- internlm/core/scheduler/pipeline_scheduler.py
- internlm/initialize/launch.py
- internlm/solver/optimizer/store.py
Fix ci train error and lint error.
> fix(ci): fix ci train error

- internlm/core/scheduler/pipeline_scheduler.py
1. Fix tensor shape error between pipeline parallel stage.
2. Fix communication blocking in pipeline parallel first stage(virtual stage wrongly set).
**Before PR**:
> fix(pipeline_scheduler.py): fix tensor shape err and comm block

- .github/workflows/demo_in_readme.yaml
- .github/workflows/lint_check.yaml
- .github/workflows/sonar.yaml
- ci_scripts/common/com_func.py
- ci_scripts/data/tokenizer_alpaca.sh
- ci_scripts/data/tokenizer_chinese.sh
- ci_scripts/model/convert_to_hf.sh
- ci_scripts/model/demo_load_7B_chat_model.py
- ci_scripts/train/ci_7B_sft.py
- ci_scripts/train/generate_config.py
- ci_scripts/train/load_ckpt.sh
- ci_scripts/train/slurm_train.sh
- ci_scripts/train/test_config.json
- ci_scripts/train/torchrun.sh
1. add load ckpt cases and common function
**Before PR**:
**After PR**:
> test(ci_scripts): add load ckpt cases

- README-zh-Hans.md
- README.md
> Update readme for news of InternLM-Chat-7B-v1.1 and Lagent

- README-ja-JP.md
- README-zh-Hans.md
- README.md
> Update readme related to internlm-chat-7v-v1.1

- README-zh-Hans.md
- README.md
LMDeploy supports 4-bit internlm-chat-7b model
README
**Before PR**:
**After PR**:
> Introduce how to deploy 4-bit quantized internlm model

- internlm/utils/simple_memory_profiler.py
- train.py
1. Remove activation_conf to imporve usability.
2. Support num_chunk > 1.
3. Give the memory layout as early as possible to avoid program crashes that cause the calculated information to fail to output.
4. Update test cases.
> feat(memory_profiler): improve memory profiler

- configs/7B_sft.py
- internlm/initialize/launch.py
- internlm/model/embedding.py
- internlm/model/linear.py
- internlm/model/modeling_internlm.py
- internlm/model/multi_head_attention.py
- internlm/utils/evaluation.py
move the sequence_parallel to parallel config
**Before PR**:
> fix(*): move sequence_parallel to parallel config

- internlm/data/utils.py
Support streaming dataset.
Add `"code"` dataset type in `internlm/data/utils.py`:
```shell
DATASET_TYPE_IDS_MAP = {"en": 0, "cn": 1, "code": 2}
```
> feat(data/utils.py): add new dataset type code for streaming dataset

- internlm/core/trainer.py
- internlm/initialize/launch.py
- internlm/utils/writer.py
- train.py
fix tensorboard resume bug
add `tensorboard_folder` in `TrainState` and make it persistent.
**Before PR**:
**After PR**:
> fix(writer): fix tensorboard resume bug

- internlm/solver/optimizer/hybrid_zero_optim.py
- train.py
Return grad norms when overflow occurs.
**Before PR**:
> fix(train.py): fix overflow grad norm error

- ci_scripts/train/load_ckpt.sh
- ci_scripts/train/slurm_train.sh
- ci_scripts/train/torchrun.sh
- internlm/utils/model_checkpoint.py
- train.py
Save the text content (binary format) of the model configuration file into checkpoint.
**Before PR**:
**After PR**:
> feat(ckpt): add model config file into ckpt

- internlm/model/embedding.py
fix(RotaryEmbedding): Fix the error that RotaryEmbedding is converted to a non-fp32 format during operation
1. The previous implementation of RotaryEmbedding will cause inv_freq and scale to be converted to non-fp32 formats during the training process, because the previous implementation mounted these 'parameters' on the buffer.
2. Add two forward methods to be compatible with the forward process of llama2.
1. Only treat inv_freq and scale as class attributes.
2. Add two forward methods.
> fix(RotaryEmbedding): Fix the error that RotaryEmbedding is converted to a non-fp32 format during operation

- internlm/utils/evaluation.py
StreamingDataset does not have __len__ method. However, due to the wrong order of a certain condition, an attempt will still be made to use the __len__ method on the StreamingDataset:
Switching the order of conditions, when it is detected that StreamingDataset is used, it no longer tries to judge len.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep …
> fix(eval): StreamingDataset does not have a __len__ method.

- internlm/initialize/initialize_tensor.py
Implement uniform_init for tensor.
train_internlm need to use different kinds of initialization.
Implement uniform_init methods for tensor.
> feat(model): implement uniform_init for tensor.

- doc/en/install.md
- doc/install.md
- docker.Makefile
- docker/Dockerfile-centos
- docker/Dockerfile-ubuntu
- experiment/Dockerfile-centos
- experiment/Dockerfile-ubuntu
- experiment/README-CN.md
- experiment/README-EN.md
- internlm/core/trainer.py
- internlm/initialize/initialize_tensor.py
- internlm/model/metrics.py
- internlm/utils/evaluation.py
- requirements/runtime.txt
[Daily Pull] Merge Main to Develop 20230901
> [Daily Pull] Merge Main to Develop 20230901

- internlm/model/linear.py
- internlm/model/modeling_internlm.py
The MLP module is lack of  "IS_TENSOR_PARALLEL" attribute.
[https://github.com/InternLM/InternLM/issues/267](https://github.com/InternLM/InternLM/issues/267)
1. internlm/model/modeling_internlm.py 
2. internlm/model/linear.py 
**Before PR**:
> fix(model): set tensor parallel attribute for mlp

- internlm/initialize/launch.py
- internlm/monitor/__init__.py
- internlm/monitor/alert.py
- internlm/train/training_internlm.py
- train.py
add light monitor.
**Before PR**:
**After PR**:
> feat(monitor): add light monitor

- internlm/utils/storage_manager.py
- tests/test_utils/common_fixture.py
- tests/test_utils/test_model_checkpoint.py
- tests/test_utils/test_storage_manager.py
The API of the `StorageManager` has been refactored, addressing parameter mismatch issues and simplifying the parameter-passing logic. Additionally, unit tests of `StorageManager` have been added.
**Before PR**:
**After PR**:
> fix(storage): refactor and fix storage_manager api

- internlm/solver/optimizer/hybrid_zero_optim.py
- internlm/utils/model_checkpoint.py
1. fix only_load tuple convert bug.
2. fix reload_zero_fp32_buff copy bug
**Before PR**:
**After PR**:
> fix(ckpt): fix checkpoint reload bug

- internlm/solver/optimizer/hybrid_zero_optim.py
Fix the bug that when put broadcast op in a stream, we need to do cuda synchronise in advance.
> fix: fix the bug to do bcast in a stream

- configs/7B_sft.py
- internlm/initialize/launch.py
- internlm/solver/optimizer/hybrid_zero_optim.py
- internlm/solver/optimizer/utils.py
- internlm/train/training_internlm.py
- internlm/utils/gputest.py
- internlm/utils/megatron_timers.py
- train.py
> feat: add runtime diag

- internlm/utils/model_checkpoint.py
- tests/test_utils/common_fixture.py
- tests/test_utils/test_model_checkpoint.py
fix snapshot none load error and remove file lock
**Before PR**:
**After PR**:
> fix(ckpt): fix snapshot none load error and remove file lock

- tests/test_model/test_embedding.py
- tests/test_model/test_model_internlm.py
- tests/test_model/test_norm.py
Add unitest for layer and model.
3 new unitests for embedding, norm, model_internlm respectively.
**Before PR**:
**After PR**:
> feat: add unitest for model

- doc/code-docs/locales/en/LC_MESSAGES/checkpoint.po
- doc/code-docs/locales/en/LC_MESSAGES/usage.po
- doc/en/usage.md
- doc/usage.md
- internlm/utils/model_checkpoint.py
Update doc quickstart usage.
**Before PR**:
> docs(doc/code-docs): update quickstart usage

- internlm/core/trainer.py
- internlm/train/training_internlm.py
- train.py
implement  [[Feature] 更精确全面的tgs统计](https://github.com/pjlab-sys4nlp/train_internlm/issues/118)
new statistics and computation for tgs
**Before PR**:
**After PR**:
> feat: more tgs

- tests/test_optimizer.py
- tests/test_solver/test_optimizer.py
add optimizer_unitest
test_optimizer.py for optimizer_unitest
**Before PR**:
**After PR**:
> feat: add optimizer_unitest

- tools/transformers/modeling_internlm.py
The final part of `streaming_chat` in `modeling_internlm.py` is not correct. The if statement should be `if res is None` then return otherwise yield.
`tools/transformers/modeling_internlm.py`
If this PR introduces a new feature, it is better to list some use cases here and …
> fix(tools): fix yield bug in stream_chat

- .github/workflows/demo_in_readme.yaml
- ci_scripts/common/variables.sh
- ci_scripts/data/tokenizer_alpaca.sh
- ci_scripts/data/tokenizer_chinese.sh
- ci_scripts/model/convert_to_hf.sh
- ci_scripts/train/load_ckpt.sh
- ci_scripts/train/slurm_train.sh
- ci_scripts/train/torchrun.sh
1. move ci env to new cluster
2. change rm action to mv
3. use spot to accelerate getting resources
4. add timeout in other job
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with …
> test(ci_scripts): move ci env

- internlm/model/linear.py
- internlm/model/modeling_internlm.py
- internlm/model/utils.py
Optimize mlp using jit
internlm/model/linear.py
internlm/model/utils.py
**Before PR**:
> feat(linear): optimize mlp by using jit 

- internlm/initialize/launch.py
- internlm/utils/gputest.py
- train.py
To do garbage collection manually.
Close automatic gc. Do gc manually.
**Before PR**:
**After PR**:
> Feat(PythonGC): Do garbage collection manually

- internlm/utils/model_checkpoint.py
- internlm/utils/storage_manager.py
- tests/test_utils/test_storage_manager.py
Fix incorrect behavior of `try_get_storage_backend` when no path prefix is provided and add more ci test for `storage_manager.py`
**Before PR**:
**After PR**:
> fix(storage): fix try_get_storage_backend

- doc/en/usage.md
- doc/usage.md
add dynamic ntk into doc
**Before PR**:
**After PR**:
> doc(usage): add dynamic ntk into doc

- configs/7B_sft.py
add auto_resume annotation into example config
**Before PR**:
**After PR**:
> Doc(config): add auto_resume annotation into example config

- README-ja-JP.md
- README-zh-Hans.md
- README.md
fix readme.md internlm huggingface url to https://huggingface.co/internlm
**Before PR**:
**After PR**:
> fix(doc): fix huggingface url

- internlm/core/scheduler/pipeline_scheduler.py
- internlm/solver/optimizer/hybrid_zero_optim.py
- internlm/train/utils.py
When enable mixed precision, pipeline will failed due to some check. This PR remove some check in pipeline_scheduler.py. It also fixes the bug when only the last pipeline stage have fp32 groups (such as the norm of output layer). In this case, old codes will create inconsistent groups number in different pipeline state.
1. internlm/core/scheduler/pipeline_scheduler.py: set self.dtype from config instead of the param groups. Also add dtype assertion in send_forward to …
> fix(pipeline): fix bugs for pipeline when enable mixed precision

- configs/7B_MoE4_sft.py
- internlm/initialize/launch.py
- internlm/utils/simple_memory_profiler.py
fix moe compatibility for fsdp and memory profiling
1. internlm/initialize/launch.py: fix arg_sanity_check(.) for fsdp compatibility 
2. internlm/utils/simple_memory_profiler.py: fix memory profiling for output type check
3. update moe config file
**Before PR**:
**After PR**:
> fix(moe): fix moe compatibility for fsdp and memory profiling

- internlm/utils/model_checkpoint.py
Since the param groups have more than one group and new attributes are added in param group (e.g. db_mode) in recent updates, this pr fix its compatibility for old ckpt.  
internlm/utils/model_checkpoint.py: align groups for new added feature, which consists of  groups attributes and learning schedule info. 
**Before PR**:
**After PR**:
> fix(ckpt): fix multipy group optimizer compatibility for old ckpt

- internlm/monitor/monitor.py
- internlm/monitor/utils.py
send exception message to light monitor
`internlm/monitor/monitor.py`
`internlm/monitor/utils.py`
> feat(monitor): send exception to light monitor

- .github/workflows/weekly_test.yaml
- tests/test_core/test_pipeline.py
- tests/test_model/test_model_internlm.py
- tests/test_solver/test_optimizer.py
- tests/test_utils/common_fixture.py
- tests/test_utils/test_storage_manager.py
Something in the code has been changed. Unitest needs to adapt them and add to CI.
Test/unitest
**Before PR**:
**After PR**:
> Fix: unitest new adaptation

- internlm/core/context/parallel_context.py
- internlm/core/scheduler/pipeline_scheduler.py
1. Fix the assert error when  InterleavedPipelineScheduler is used. In such case, comm.send_×××(.) may send None in the last pipeline stage and the origin assert condition will fail [here](https://github.com/InternLM/InternLM/blob/2c5395fdfd5106f353a3894820b75ec3cd1dc43a/internlm/core/scheduler/pipeline_scheduler.py#L984)
2. Fix the tensorborad writing bug when InterleavedPipelineScheduler is used. The old is_no_pp_or_last_stage(.) in [record_current_batch_training_metrics](https://github.com/InternLM/InternLM/blob/2c5395fdfd5106 …
> fix(pipeline): fix interleave type assert and metrics error

- .github/workflows/unit_tests.yaml
1. add unit test yaml on pr stage
**Before PR**:
**After PR**:
> test(workflow): add unit test yaml

- internlm/solver/optimizer/hybrid_zero_optim.py
- internlm/solver/optimizer/utils.py
- internlm/train/training_internlm.py
- internlm/utils/parallel.py
计算layer norm，添加至tensorboard，并通过 config中的`grad_norm_profiling`开关来控制是否启用
`internlm/solver/optimizer/hybrid_zero_optim.py`
`internlm/solver/optimizer/utils.py`
`internlm/train/training_internlm.py`
`internlm/utils/parallel.py`
**Before PR**:
> feat(optimizer): add layer norm to tensorboard

- tools/transformers/tokenization_internlm.py
https://github.com/InternLM/InternLM/issues/400
`tools/transformers/tokenization_internlm.py`: simply move code of initialization.
**Before PR**:
**After PR**:
> fix(tools): fix InternLMTokenizer to fit transformers==4.34.0

- internlm/core/context/__init__.py
- internlm/core/context/parallel_context.py
- internlm/model/modeling_internlm.py
- internlm/solver/optimizer/hybrid_zero_optim.py
fix the all-reduce bug for norm in sequence parallel.
> fix(*)/all-reduce for norm in sequence parallel

- internlm/solver/optimizer/hybrid_zero_optim.py
> fix broadcast synchronize()

- internlm/solver/optimizer/hybrid_zero_optim.py
> fix(optimizer)/add broadcast synchronize

- internlm/solver/optimizer/hybrid_zero_optim.py
> fix(optimizer):broadcast main

- internlm/solver/optimizer/hybrid_zero_optim.py
> fix(optimizer):broadcast

- internlm/solver/optimizer/hybrid_zero_optim.py
- internlm/solver/optimizer/utils.py
- internlm/train/training_internlm.py
- internlm/utils/parallel.py
添加zero gradient 统计到tensorboard，开关：`zero_grad_profiling`
`internlm/solver/optimizer/hybrid_zero_optim.py`
`internlm/solver/optimizer/utils.py`
`internlm/train/training_internlm.py`
`internlm/utils/parallel.py`
[x] 测试7B case
[x] 测试7B MoE case
> feat(optimizer): zero gradient count

- internlm/utils/storage_manager.py
> fix(os): fix FileNotFoundError in storage_manager

- web_demo.py
> fix(web_demo): remove <eoh> in user prompt

- .github/workflows/unit_tests.yaml
1. change slurm partition
If this PR introduces a new feature, it is better to list some use cases here and update the …
> test(workflow): change slurm partition

- internlm/solver/optimizer/hybrid_zero_optim.py
- internlm/train/training_internlm.py
支持可选部分layer profiling的tensorboard
`internlm/solver/optimizer/hybrid_zero_optim.py`
`internlm/train/training_internlm.py`
> feat(optimizer): optional parameter tensorboard

- README-ja-JP.md
- README-zh-Hans.md
- README.md
The model_path in README's example is not proper.
**Before PR**:
**After PR**:
> fix(readme): fix model_path in readme

- internlm/data/packed_dataset.py
> fix(data): broadcast list when walking dataset folders to avoid problems

- internlm/data/packed_dataset.py
- internlm/data/utils.py
- internlm/train/training_internlm.py
> feat(data): walk folder to get dataset_type_ids_map

- tools/transformers/convert2hf.py
转换脚本未能正确设置 bos eos pad 导致 hf  模型的生成出现问题
在转换脚本中使用 tokenizer 保存 bos eos pad
**Before PR**:
**After PR**:
> fix(tools): set bos, eos, pad in convert2hf to fix improper generation

- README-ja-JP.md
- README-zh-Hans.md
- README.md
The lack of parameter `torch_dtype` in README may confuse the users.
Add torch_dtype to README examples.
**Before PR**:
**After PR**:
> feat(doc): add torch_dtype to examples in README

- tests/test_training/7B_check_acc.py
- tests/test_training/train_CI.py
Check whether the weights are within the error range every 100 steps.
A specific config ./tests/test_training/7B_check_acc.py
A train_CI.py for checking. 
**Before PR**:
**After PR**:
> Feat(QA): Check model weights for acc

- internlm/initialize/launch.py
- internlm/monitor/alert.py
launch light monitoring on all ranks
`internlm/initialize/launch.py`
`internlm/monitor/alert.py`
> feat(monitor): init light monitoring on all ranks

- internlm/solver/optimizer/hybrid_zero_optim.py
- internlm/train/training_internlm.py
> fix(grad_norm): rename vars

- internlm/model/metrics.py
when validation loss > 20, there is of high probability that ppl exceed the range of float16
change the stored variable to float32
> fix(metric): use float32 to compute ppl

- internlm/utils/model_checkpoint.py
save ckpt when reach total step count
**Before PR**:
**After PR**:
> feat(ckpt): save ckpt when reach total step count

- .gitignore
- internlm/train/training_internlm.py
> fix(data): fix dataset types when using random dataset

- internlm/train/training_internlm.py
- internlm/utils/common.py
- internlm/utils/writer.py
- train.py
> fix(train): unify the paths

- tests/test_training/7B_check_init.py
- tests/test_training/train_CI.py
Check init model weights
train_CI.py
7B_check_init.py
**Before PR**:
**After PR**:
> Feat(QA): Check init model weights

- configs/7B_sft.py
- internlm/core/context/parallel_context.py
- internlm/core/scheduler/base_scheduler.py
- internlm/core/scheduler/no_pipeline_scheduler.py
- internlm/core/scheduler/pipeline_scheduler.py
- internlm/initialize/launch.py
- internlm/utils/evaluation.py
- tests/test_core/test_pipeline.py
- tests/test_core/utils.py
- tests/test_data/test_batch_sampler.py
Support rampup batch_size or variable batch size.
**Before PR**:
**After PR**:
> feat(train): support rampup batch_size

- .github/workflows/pr_before_merge.yaml
1. add model init test
If this PR introduces a new feature, it is better to list some use cases here and update the …
> test(workflow): add model init test

- internlm/initialize/launch.py
- internlm/model/modeling_internlm.py
Fix seed for every model initialization 
model_internlm.py : fix_seed()
launch.py: GLOBAL_SEED
**Before PR**:
**After PR**:
> feat(seed): set global seed for every model initialization

- internlm/utils/common.py
- internlm/utils/timeout.py
根据实际情况，调大初始化model和optimizer的timeout
> fix(timeout): larger timeout

- internlm/model/modeling_internlm.py
- internlm/model/multi_head_attention.py
Add the rope_base interface to adapt to the need to modify the base.
Add the rope_base interface to adapt to the need to modify the base.
Add the rope_base interface.
**Before PR**:
**After PR**:
> feat(model): add rope_base interface

- tests/test_training/test_swap_nb_loss_and_gradnorm.py
> Fix(QA): the py name in main is wrong

- configs/7B_sft.py
- internlm/core/scheduler/pipeline_scheduler.py
- internlm/initialize/launch.py
- internlm/utils/evaluation.py
- internlm/utils/gputest.py
- tests/test_training/train_CI.py
- train.py
1. fix(config): `rampup_batch_size `defalut value BC.
2. fix(config): standardize config parameter access.
3. feat(launch): add `warmup_process_group`
4. feat(memory): add `cuda_memory_analyze`
**Before PR**:
**After PR**:
> fix/feat: small fix and enhancement

- .github/workflows/pr_merged.yaml
- .github/workflows/weekly_test.yaml
1. add workflow for loss test 
2. change trigger event for weekly_test
If this PR introduces a new feature, it is better …
> test(workflow): add workflow for loss test and change trigger event

- tests/test_utils/common_fixture.py
- tests/test_utils/test_model_checkpoint.py
> fix(ci): fix test model ckpt ci test

- .github/workflows/unit_tests.yaml
add unit test case
If this PR introduces a new feature, it is better to list some use cases here and update the …
> test(workflow): add unit test case

- internlm/initialize/launch.py
- internlm/utils/model_checkpoint.py
- internlm/utils/storage_manager.py
- tests/test_utils/common_fixture.py
- tests/test_utils/test_storage_manager.py
> feat(storage): use multipart upload when using oss

- tests/test_utils/test_model_checkpoint.py
> Fix (QA checkpoint): fix test_model_checkpoint singleton import 

- internlm/core/naive_amp.py
- internlm/model/modeling_internlm.py
添加开关 output_tf32，控制output层是否使用tf32精度.
> feat(model): add output embedding tf32 option

- internlm/initialize/launch.py
- internlm/solver/optimizer/hybrid_zero_optim.py
- internlm/solver/optimizer/utils.py
- internlm/train/training_internlm.py
- train.py
支持output层 vocab 粒度的grad norm profiling.
grad norm config:
```
grad_profiling = dict(
grad_norm_profiling=False,
zero_grad_profiling=False,
layers=["ScaleColumnParallelLinear"],
vocab_grad_norm_profiling=False,
interval_steps=5,
)
```
`internlm/solver/optimizer/hybrid_zero_optim.py`
`internlm/solver/optimizer/utils.py`
`internlm/train/training_internlm.py`
> feat(grad_norm): vocab grad norm profiling

- tests/test_data/test_batch_sampler.py
> fix(test): fix type_ids unpack bug

- configs/7B_sft.py
- internlm/model/__init__.py
- internlm/model/modeling_llama.py
- internlm/utils/model_checkpoint.py
- tools/transformers/internlm_model/modeling_internlm.py
support to load llama checkpoint
**Before PR**:
**After PR**:
> feat(model): support llama model with checkpoint loading

- internlm/solver/optimizer/hybrid_zero_optim.py
fix the norm all-reduce in sequence parallel when overlap is False.
**Before PR**:
> fix(sequence_parallel): fix norm all-reduce in seq_parallel when not overlaping

- internlm/core/engine.py
- internlm/core/scheduler/base_scheduler.py
- internlm/core/scheduler/no_pipeline_scheduler.py
- internlm/core/scheduler/pipeline_scheduler.py
- internlm/utils/common.py
- tests/test_data/test_batch_sampler.py
> fix(pp): fix no-packed dataset load micro batch error

- configs/7B_MoE4_sft.py
- internlm/solver/optimizer/hybrid_zero_optim.py
The old code would set the zero mode as Parallel.Data. This PR fixes it and sets the zero mode to be Parallel.ExpertData.
Right logic:
* If zero is not used, set all param group as ParallelMode.ZERO1. 
* If zero is used, expert dp group will use ParallelMode.EXPERT_DATA as the real zero mode; set others as ParallelMode.ZERO1
If so, please describe how it …
> fix(moe): fix moe zero mode bug

- internlm/solver/optimizer/utils.py
> fix(grad_norm): token grad norm with tp

- .github/workflows/demo_in_readme.yaml
- .github/workflows/e2e_test.yaml
- .github/workflows/pr_before_merge.yaml
- .github/workflows/pr_merged.yaml
- .github/workflows/unit_tests.yaml
- ci_scripts/data/tokenizer_chinese.sh
- ci_scripts/train/load_ckpt.sh
- ci_scripts/train/slurm_train.sh
- ci_scripts/train/torchrun.sh
1. change submit way avoid of job being canceled frequently
If this PR introduces a new feature, it is better to list some …
> test(workflow): change into reserved

- README-ja-JP.md
- README-zh-Hans.md
- README.md
> fix(readme): fix deprecated model path in code examples

- tools/tokenizer.py
`tools/tokenizer.py`: set `add_tos_token=True`
**Before PR**:
**After PR**:
> fix(tools): set `add_eos_token=True` in tokenizer.py

- internlm/model/metrics.py
> fix(metrics): remove redundant cuda memory in metric calculations

- internlm/core/scheduler/no_pipeline_scheduler.py
- internlm/core/scheduler/pipeline_scheduler.py
only perform allreduce when num_expert is set in model config or num_expert  is 1.
**Before PR**:
**After PR**:
> fix(pipeline): avoid allreduce for dense model

- chat/openaoe.md
- chat/openaoe_zh_cn.md
add openaoe docs
If this PR introduces a new feature, it is better to list some use cases here and update the …
> add openaoe docs

- README.md
- README_zh-CN.md
- chat/lmdeploy.md
- chat/lmdeploy_zh_cn.md
> update deployment guide

- README.md
- README_zh-CN.md
Fix typos in README
`README.md` and `README_zh-CN.md`
> [Docs] Fix typos in README

- chat/chat_format.md
- chat/chat_format_zh-CN.md
> [Docs] chat format

- finetune/README.md
- finetune/README_zh-CN.md
> [Doc]: Add XTuner docs

- chat/openaoe.md
- chat/openaoe_zh_cn.md
> update introduction of OpenAOE

- .owners.yml
> Update .owners.yml: disable auto assign

- chat/web_demo.py
> Update end token id inweb_demo.py

- chat/chat_format.md
- chat/chat_format_zh-CN.md
> [Doc] update chat format doc

- chat/web_demo.py
> [Fix]: Update web demo to be self-contained

- finetune/README.md
- finetune/README_zh-CN.md
> Fix invalid urls of InternEvo

- README.md
- README_zh-CN.md
> Add a figure to show the relation of different models

- README.md
- README_zh-CN.md
> [Fix] Link error

- chat/web_demo.py
1. 实测 `from transformers import AutoModelForCausalLM, AutoTokenizer` 必须先引入 `AutoTokenizer` 再引入`AutoModelForCausalLM` 否则会报以下错
```bash
Traceback (most recent call last):
File "/root/.conda/envs/InternLM/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
exec(code, module.__dict__)
File "/root/code/InternLM2/web_demo.py", line 10, in <module>
from transformers import AutoModelForCausalLM, AutoTokenizer
ImportError: cannot import name 'AutoModelForCausalLM' from 'transformers' (/root/.local/lib/python3.10/site-packages/transformers/__init__.py)
load model begin.
```
2. 必须用 steamlit 命令，不能用 python 命令运行 web_demo.py 否则会报以下错
``` bash
2024-01-19 15:02:13.807 Session state does not function when running a script without `streamlit run`
Traceback …
```
> [Fix Bugs] Update web_demo.py

- chat/chat_format.md
- chat/chat_format_zh-CN.md
- chat/web_demo.py
- `<|im_start|>`：每个角色对话的开始符，在词表中对应的 token ID 是**92543**
- `<|im_end|>`：每个角色对话的结束符，在词表中对应的 token ID 是**92542**
- `<|action_start|>`：模型调用外部工具(代码解释器或外部插件)的开始符，在词表中对应的 token ID 是**92541**
- `<|action_end|>`：模型调用外部插件的结束符，在词表中对应的 token ID 是**92540**
- `<|interpreter|>`：代码解释器，在词表中对应的 token ID 是**92539**
- `<|plugin|>`：外部插件，常规的 tools，在词表中对应的 token ID 是**92538**
```
<|im_start|>system
你是书生浦语2，一个无害的人工智能助手<|im_end|>
<|im_start|>system name=<|plugin|>
[
{
"name": "get_current_weather",
"description": "Get the current weather in a given location",
"parameters": {
"type": "object",
"properties": {
"location": {
"type": "string",
"description": "The city and state, e.g. San Francisco, CA",
},
"unit": {"type": "string"},
},
"required": ["location"],
},
}
]
<|im_end|>
<|im_start|>user …
```
> [Enchance] update chat format

- README.md
- README_zh-CN.md
Add InternLM-Math
Update markdown.
**Before PR**:
**After PR**:
> Add InternLM-Math

- README.md
- README_zh-CN.md
Related to old pull request:
https://github.com/InternLM/InternLM/pull/621
> Add bitsandbytes to Readme,and support usage on low-resource devices.

- .github/workflows/daily_tests.yaml
- tests/test_hf_model.py
add basic model test
**Before PR**:
**After PR**:
> test(workflow): add basic model test

- README.md
- README_zh-CN.md
- requirements.txt
> [doc]  Add the requirement for the transformers library version in usage section

- .github/workflows/daily_tests.yaml
> add transformers version converage

- model_cards/internlm2_1.8b.md
> [Doc] add internlm2-1.8b model card

- README.md
- README_zh-CN.md
> add 200k-long-context inference section in README

- tools/convert2llama.py
> [Tool]: Update tools/convert2llama.py to support `safetensors` format

- tools/convert2llama.py
After converting using tools/convert2llama.py to LLama architecture, I encountered an error when loading with transformers.
fixes #731 
use save_file to save file …
> fix the issue of safetensors conversion LLama error

- agent/README.md
- agent/README_zh-CN.md
- agent/streaming_inference.py
> [Feat] Support batch inference in agents

- tests/test_hf_model.py
add this two models into daily testcase
'internlm/internlm2-math-plus-1_8b'
'internlm/internlm2-math-plus-7b'
testworkflow is https://github.com/InternLM/InternLM/actions/runs/9312966732/job/25634596647
> Add newest math model into daily testcase

- ecosystem/README.md
- ecosystem/README_zh-CN.md
> Update internlm2 ecosystem

- README.md
- README_zh-CN.md
- model_cards/internlm2.5_7b.md
> Add guidance about 4bit quantized model deployment

- README.md
- README_zh-CN.md
- model_cards/internlm2_reward.md
> docs: internlm2-reward readme

- chat/web_demo.py
Transformers `_get_logits_warper` method add a new param `device` in version 4.42.0.
Add `device` for `web_demo` when calling `_get_logits_warper`.
> [Fix] web demo support new version transformers

- README.md
- ecosystem/README.md
- ecosystem/README_zh-CN.md
Add LazyLLM and its usage to ecosystem/README.md
Add LazyLLM and its usage to ecosystem/README.md
The three examples given in the document have been verified:
1. Chatbot: 
2. RAG: 
3. Finetune: 
**Before PR**:
**After PR**:
> Add LazyLLM and its usage to ecosystem/README.md

- README.md
- README_zh-CN.md
Repo 内没有地方可以直接跳转到浦语应用和 API。用户不知道可以直接使用 API 使用 InternLM2.5
README 内增加浦语 ChatWeb 和 URL 跳转
> README 内增加浦语 ChatWeb 和 URL 跳转

- README.md
- README_zh-CN.md
InternLM has been launched in the modelers community. Please add a link to the ReadME.md. Please review,thanks.
> Add modelers to README.md

- README.md
- README_zh-CN.md
> [Docs] Update README.md

- README.md
> docs: add SGLang

- README.md
- README_zh-CN.md
- ecosystem/README.md
- ecosystem/README_zh-CN.md
Update doc for internlm3
**Before PR**:
**After PR**:
> [Doc]: Update doc for internlm3

- ecosystem/README_npu.md
- ecosystem/README_npu_zh-CN.md
Update README_npu
Update README_npu
**Before PR**:
**After PR**:
> [Doc]: Update README_npu
